---

- hosts: all  # run this against all the servers
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always    # "always" tags are necessary
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes  # to tell ansible use a remote source as in the above url
        owner: root
        group: root
        mode: 0755 

- hosts: web_servers   # run this task only against "web_servers"
  become: true
  tasks: 

  - name: install apache and php packages for Ubuntu servers
    tags: apache,apache2,ubuntu  # you can whatever tags you want
    apt:     
      name: 
      - apache2
      - libapache-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages for CentOS
    tags: apache,httpd,centos
    dnf:
      name: 
      - httpd
      - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html     # ansible assume the directory to be "files"
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt: 
      name: mariadb-server 
      state: latest 
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package: 
      name: samba
      state: latest 
